FROM node:22.12.0 AS build
WORKDIR /app

COPY package*.json ./
COPY frontend/package*.json frontend/

RUN --mount=type=cache,target=/root/.npm npm ci --workspace frontend

COPY frontend ./frontend

ARG VITE_API_URL=http://backend:777
ENV VITE_API_URL=${VITE_API_URL}
WORKDIR /app/frontend
RUN npm run build

EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]
