FROM node:22.12.0 AS deps
WORKDIR /app

COPY package*.json ./

COPY backend/package*.json backend/

RUN npm ci --omit=dev --workspace backend

COPY backend ./backend

ENV NODE_ENV=production

ENV PORT=777

WORKDIR /app/backend

EXPOSE 777

CMD ["npm", "start"]
